// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnPgE9w3vuFEH0PrDslfdnYLI8gf80L5o',
    appId: '1:642081477287:ios:8c065356f641ba7f1b8182',
    messagingSenderId: '642081477287',
    projectId: 'productivity-67d4b',
    storageBucket: 'productivity-67d4b.appspot.com',
    iosBundleId: 'com.example.productivity048755.mlrd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnPgE9w3vuFEH0PrDslfdnYLI8gf80L5o',
    appId: '1:642081477287:ios:a89bc025fdd140e31b8182',
    messagingSenderId: '642081477287',
    projectId: 'productivity-67d4b',
    storageBucket: 'productivity-67d4b.appspot.com',
    iosBundleId: 'com.example.productivity',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG8cQTG1toa42neHKnum72IOayVjmwx5A',
    appId: '1:642081477287:web:76304fa0ac1fd3ca1b8182',
    messagingSenderId: '642081477287',
    projectId: 'productivity-67d4b',
    authDomain: 'productivity-67d4b.firebaseapp.com',
    storageBucket: 'productivity-67d4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK48Byu15eU4CkAMTRPGysn9Ffk-5RrEk',
    appId: '1:642081477287:android:56aac40fe2fb4ee81b8182',
    messagingSenderId: '642081477287',
    projectId: 'productivity-67d4b',
    storageBucket: 'productivity-67d4b.appspot.com',
  );

}